variable "logs_retention" {}
variable "application_name" {}
variable vpc_cidr_block {}
variable vpc_name {}
variable "availability_zones" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "common_tags" {}
variable "vpc_flow_logging_role_arn" {}