variable "sg_kubernetes_node_asg" {}
variable "kubernetes_node_role" {}
variable "ami" {}
variable "sg_control_plane" {}
variable "sg_jenkins" {}
variable "common_tags" {}
variable "private_subnet_ids" {}
variable "application_name" {}
variable "kubernetes_control_plane_role" {}